version: '3.8'
services:
#  localstack:
#    image: localstack/localstack:latest
#    container_name: localstack
#    ports:
#      - "4566:4566"
#    environment:
#      - SERVICES=s3
#      - DEBUG=1
#    volumes:
#      - "./s3-buckets-init.sh:/etc/localstack/init/ready.d/s3-buckets-init.sh"
#      - "./localstack_data:/var/tmp/localstack"
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=dummy-key-id
      - MINIO_ROOT_PASSWORD=dummy-key-secret
    command: server /data --console-address ":9001"
    volumes:
      - ./minio_data:/data
  createBucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 dummy-key-id dummy-key-secret;
      /usr/bin/mc mb myminio/digimon-meta-dev-bucket;
      /usr/bin/mc anonymous set public myminio/digimon-meta-dev-bucket;
      exit 0;
      "
  wiremock:
    image: wiremock/wiremock
    container_name: wiremock-kakao
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    environment:
      - WIREMOCK_PORT=8080
    restart: always
    command: >
      /bin/sh -c "
      mkdir -p /home/wiremock/mappings && \
      echo '{
        \"request\": {
          \"method\": \"GET\",
          \"urlPattern\": \"/oauth/authorize\?.*\"
        },
        \"response\": {
          \"status\": 302,
          \"headers\": {
            \"Location\": \"http://localhost:50000/login/kakao?code=mock_auth_code\"
          }
        }
      }' > /home/wiremock/mappings/kakao-authorize.json && \
      echo '{
        \"request\": {
          \"method\": \"POST\",
          \"urlPattern\": \"/oauth/token\?.*\"
        },
        \"response\": {
          \"status\": 200,
          \"body\": \"{ \\\"access_token\\\": \\\"mock_access_token\\\", \\\"token_type\\\": \\\"bearer\\\", \\\"expires_in\\\": 3600, \\\"refresh_token\\\": \\\"mock_refresh_token\\\", \\\"scope\\\": \\\"profile\\\" }\",
          \"headers\": {
            \"Content-Type\": \"application/json\"
          }
        }
      }' > /home/wiremock/mappings/kakao-token.json && \
      echo '{
        \"request\": {
          \"method\": \"GET\",
          \"urlPattern\": \"/v2/user/me.*\"
        },
        \"response\": {
          \"status\": 200,
          \"body\": \"{ \\\"id\\\": 123456789, \\\"properties\\\": { \\\"nickname\\\": \\\"mock_nickname\\\" } }\",
          \"headers\": {
            \"Content-Type\": \"application/json\"
          }
        }
      }' > /home/wiremock/mappings/kakao-user-info.json && \
      exec /docker-entrypoint.sh --local-response-templating"
