spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/data/demo
  application:
    name: Digimon-Meta-Dev
  cloud:
    consul:
      config:
        enabled: true
      port: 8500
      host: 192.168.50.199
  config:
    import: "consul:"
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/
admin:
  id: adminJoo
  password: adad23415
jwt:
  secret: kfqwokfpqgfjopjagopjsgopjapg213123jaipgasfasdas
  expiration-ms: 360000000
img:
  original: test/original/images/
  small: test/small/images/
