spring:
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
  datasource:
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/demo;AUTO_SERVER=TRUE
  application:
    name: Digimon-Meta-Dev
  cloud:
    consul:
      config:
        enabled: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: kakao
            client-id: dummy-client-id
            redirect-uri: localhost:50000
        provider:
          kakao:
            authorization-uri: http://localhost:8089/oauth/authorize
            token-uri: http://localhost:8089/oauth/token
            user-info-uri: http://localhost:8089/v2/user/me
admin:
  id: adminJoo
  password: adad23415
jwt:
  secret: kfqwokfpqgfjopjagopjsgopjapg213123jaipgasfasdas
  expiration-ms: 360000000
img:
  original: test/original/images/
  small: test/small/images/
aws:
  s3:
    endpoint: http://127.0.0.1:9000
  access-key-id: dummy-key-id
  access-key-secret: dummy-key-secret

s3:
  bucket-name: digimon-meta-dev-bucket
back:
  digimon: https://digimon-meta.site/images/digimon_back.png
  digitama: https://digimon-meta.site/images/digitama_back.png
domain:
  url: http://127.0.0.1:9000/digimon-meta-dev-bucket/

