spring:
  cloud:
    consul:
      config:
        enabled: false
    aws:
      secretsmanager:
        enabled: true
        default-context: digimon-meta-prod  # 기본 시크릿 이름 (AWS Secrets Manager에 저장된 이름)
        prefix: /  # 시크릿 경로의 루트 설정
        fail-fast: true  # 시크릿을 가져오지 못하면 애플리케이션이 실패하도록 설정
  application:
    name: Digimon-Meta
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
            client-name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/
